### ISSUE TITLE
New skins through store

### ISSUE THREAD

**Issue by claybruh** [eflip/LittlefootCMS#153]
Trying to upload a test skin via store, but it's not working nor is it kicking any error messages.

ZIP url: claytonfryar.com/cockybadger/lf/skins/XV.zip
App name: testing

Tried on a couple different LF installs, both on and off the HD reseller.

**Comment by bioshazard** [comment]
Fixed in https://github.com/eflip/LittlefootCMS/pull/166 

Given a zip with contents:

```
./myskinname
./myskinname/index.php
./myskinname/css/custom.css
```

You can select to download a skin type from a given .zip url (works well for github ;)

![image](https://cloud.githubusercontent.com/assets/5616668/13767596/5f08f4c6-ea42-11e5-9026-0b204aadb8fc.png)

Im going for a kinda yum repo situation for apps, skins, and plugins

**Comment by bioshazard** [comment]
https://github.com/eflip/LittlefootCMS/pull/166
